### ISSUE TITLE
Dirty french translation

### ISSUE THREAD

**Issue by chdenat** [rcmaehl/WhyNotWin11#189]
Special characters are not displayed correctly.
No words wrapping ...

**Comment by PierreGrillet** [comment]
Can we have a screen ?

**Comment by chdenat** [comment]
Sure ! I forgot it ! 

![2021-06-29 09_21_22-WhyNotWin11](https://user-images.githubusercontent.com/9724885/123773485-faf1a300-d8cc-11eb-917a-d9a361ddaf26.png)

**Comment by PierreGrillet** [comment]
Nice to ear that it runs on #Windows11 :smile: 

It seems that every language translation is affected by a file format problem (UTF-8), like [here](https://github.com/rcmaehl/WhyNotWin11/issues/186).
The french translation have to been shorten to until a general solution is provided to wrap, or make font smaller, in order to fit.

**Comment by chdenat** [comment]
yes #Microsoft just decided to open the W11 Insider  channel to PCs using Intel  7th generation  (to see if it is ok) .

Oh yes, it's a typical UTF issue ! 

I think too that font should be smaller and may be lighter (why not  a standard windows font ...) ,
Do not see the interest to have such big size !
