### ISSUE TITLE
DirectX 12 / WDDM 2.x detection needs to be tweaked

### ISSUE THREAD

**Issue by jrmoore** [rcmaehl/WhyNotWin11#22]
Something's not quite right in the way it's being detected at the moment, I just ran the app in a clearly unsupported machine, but that requirement was regarded as passed:

![image](https://user-images.githubusercontent.com/311922/123485774-10d04100-d60b-11eb-96bb-d37691494da8.png)

![image](https://user-images.githubusercontent.com/311922/123485817-2cd3e280-d60b-11eb-8f22-8105fcaa8890.png)

The title and text for the things present in the system is pixelated by the way, was it intentional?

And being pedantic here but...
- If the boot type is legacy, Secure Boot can't be enabled or disabled, that category should read "Incompatible" maybe.
- Same for TPM, rather than not activated it'd be better if it read "TPM not detected, disabled/not present"
- What's with the PascalCase all around 😜

**Comment by rcmaehl** [comment]
Odd. Can you "Save all information" in dxdiag and send me a copy of it?

> The title and text for the things present in the system is pixelated by the way, was it intentional?

I may need to increase text quality for the larger text if that's noticeable. I don't have a terribly high-res display and it's scaling is 100% so it didn't look bad for me.

>If the boot type is legacy, Secure Boot can't be enabled or disabled, that category should read "Incompatible" maybe.
Might consider it. Most modern motherboard keep Legacy boot available for backwards compatibility so I don't want to come off as telling people they don't have it at all

>Same for TPM, rather than not activated it'd be better if it read "TPM not detected, disabled/not present"
Possibly, once again, I'm hesitant to state "not present", although I may consider "disabled/not detected"

>What's with the PascalCase all around
A lot of it is the programming language being auto-completed by the IDE, but some of it is just how I program

**Comment by jrmoore** [comment]
> Odd. Can you "Save all information" in dxdiag and send me a copy of it?

Sure, although it's a really old computer (circa 2007) I don't know if it'd be relevant for newer machines.

Here: [DxDiag.txt](https://github.com/rcmaehl/WhyNotWin11/files/6718991/DxDiag.txt)

> I don't have a terribly high-res display and it's scaling is 100% so it didn't look bad for me.

Same here, it was connected to a 22'' 1080p display at 100% DPI, the title of the app was the only one that looked pixelated. The other text looked alright, although it seems to be using the same font as the title.

> Most modern motherboard keep Legacy boot available for backwards compatibility so I don't want to come off as telling people they don't have it at all.

Yep, fair enough, there's no way to actually detect whether the firmware of the system is UEFI based right? It may be better not to say it's incompatible, people is freaking out enough as it is haha.

> A lot of it is the programming language being auto-completed by the IDE, but some of it is just how I program

😊

**Comment by micwoj92** [comment]
It's easy to see the culprit now, at line 17 of your dxdiag it says "DirectX Version: DirectX 12", It makes sense that it detects it as compatible, based on how it does the detection

https://github.com/rcmaehl/WhyNotWin11/blob/0cd5e3de14a95973951dd58659297f8d64314a1f/WhyNotWin11.au3#L298

**Comment by jrmoore** [comment]
Oh! I see, I wonder if it'd be more precise to look at "DDI Version" instead.

It hold true for this machine, but I won't be able to test it in a newer, supported one, until tomorrow.

**Comment by micwoj92** [comment]
> Oh! I see, I wonder if it'd be more precise to look at "DDI Version" instead.
> 
> It holds true for this machine, but I won't be able to test it in a newer, supported one, until tomorrow.

I don't have access to any "supported" machine either, but I looked at some dxdiag outputs online and it seems to be better way than currently.

**Comment by verdy-p** [comment]
Microsoft is apparently more strict than just DirectX 12 API support, it wants drivers based on WDDM 2.
The processor list is apparently frozen to an exclusive list, instead of capabilities (which are not explained at all) The "supported" list contains various processors that are LESS capable then those that are NOT supported.

Microsoft is also not very clear about TPM 2 support, as it has various settings: SHA-1 or SHA-2 fingerprints, API: TIS or something else, on PCI bus or USB or other buses. TPM measurements are not the same depending on these settings; as well there are various crypto algorithms, not the same depending on regions. Windows 10 was initially unstable and underspecified, causing troubles to BIOS makers (that had to create various patches to get them recognized; not so many troubles with Linux or other OSes).

As well it seems that support for hardware virtualization is required, and HVSI must be enabled  (So Hyper-V must be enabled, causing troubles with other hypervisors as Hyper-V still does not support secondary level virtualization). Hyper-V is now required to integrate containers. Some legacy Intel security tools (integrated on the BIOS) also need to be disabled in BIOS settings (they are no logner supported by Intel itself).

Fially for secure boot, you must check that "CBS support" in UEFI is disabled in BIOS settings for startup: all devices must be handed over to windows drivers.

Support for extended addresses is also needed, but for now 5-level paging is not needed (supported only by very few recent processors, needed for multilyers hypervisors), but support for large pages is apparently needed, jsut like stronger requirements for DMA, and hardware memory descriptors.

All these extra are supported on my processor, as well as hardware AES (only for performance), and avanced SIMD instructions (not much details there, but may be needed by some software emulations or virtualization of audio/video codecs, or when battery saving shutdowns the GPUs or signal and network coprocessors, replaced by CPU emulation, without having to wake up these extra processing units).

You may also need some microcode support for your CPU (or activable mitigations for new side channel attacks, on various processuing units, bus drivers)
