### ISSUE TITLE
Hungarian translation is duplicated

### ISSUE THREAD

**Issue by clinche** [rcmaehl/WhyNotWin11#290]
040E.lang and 1038.lang are different duplicates of Hungarian translation.
Which one should be kept ?

**Comment by micwoj92** [comment]
Hex, please ping translator(s) to discuss which translations are better.

**Comment by clinche** [comment]
@Tudi20 & @bbence018 can you agree together on a definitive translation ?
Thanks a lot

**Comment by rcmaehl** [comment]
Yep, looks like bbence018 turned into a ghost

**Comment by micwoj92** [comment]
@Tudi20 Because you have not responded in 4 days and your translation had wrong code, I have removed it. There is 040E.lang file which you may want to review if you wish.

**Comment by Tudi20** [comment]
I barely have been on the Internet for this past few days, tbh, and I also
was waiting for the other guy to show up, since I realised that there was
already an other one.

I might review his original translation, and see which one I like better
personally.

Also, edits don't get notifications, and I don't understand why something
that practically shouldn't be translated is translatable.

Furthermore, if space is an issue that us translators should get around
then definitely it will have to be reviewed, and an easy way to preview our
translations would be appreciated.

micwoj92 ***@***.***> ezt írta (időpont: 2021. júl. 5., H
1:08):

**Comment by micwoj92** [comment]
>  I barely have been on the Internet for this past few days, tbh, and I also was waiting for the other guy to show up, since I realised that there was already an other one.

We were waiting too, but it seems like the GitHub account was deleted and we have no other way to contact.

> Also, edits don't get notifications, and I don't understand why something that practically shouldn't be translated is translatable.

I don't know what you mean by that.

> Furthermore, if space is an issue that us translators should get around then definitely it will have to be reviewed, and an easy way to preview our translations would be appreciated.

There is, you can go to `%localappdata%\WhyNotWin11\langs`, find your language code, change file and view locally. I will add it to guidelines now.
