### ISSUE TITLE
Add Scan Result Summary

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#32]
A summary table would be great to show what's possible:

Symbol | Check | Note
------------ | ------------- | -------------
OK | Win11 ready* | 
X | Upgrade** | You need a x64 bit OS.
OK | Clean install*** | 

*) Red=no; yellow=minimum requirements; green=full ready
**) red=x32 OS; green=x64 OS (and Win11 ready/min. requirements)
***) Red=Not Win11 ready; Green=Win11 ready/min. requirements

**Comment by htcfreek** [comment]
Could be interesting to classify checks based on Insider build requirements, minimal requirements, suggested requirements, and optional requirements.

**Comment by micwoj92** [comment]
Hmm, I see that in versions 1.x there were some tips. @rcmaehl why were they removed? They could be great addition to this issue.
![image](https://user-images.githubusercontent.com/45581170/124203567-4b3f4f80-dadd-11eb-9e07-09b0d8e97400.png)

**Comment by rcmaehl** [comment]
> Hmm, I see that in versions 1.x there were some tips. @rcmaehl why were they removed? They could be great addition to this issue.
> ![image](https://user-images.githubusercontent.com/45581170/124203567-4b3f4f80-dadd-11eb-9e07-09b0d8e97400.png)

Were removed during the rewrite to 2.x, I think we're finally in a state that we can add them back in due to the GUI and requirements not really changing anymore and neither is the GUI. Ideally, if someone else could write them as I suck at explaining (see v1), it'd be appreciated.

Potential icons to help indicate more info/help:
![image](https://user-images.githubusercontent.com/716581/124203924-cdaf1b80-daab-11eb-95de-a87f532246ce.png)

**Comment by micwoj92** [comment]
question mark 4 definitely. I think that these tips should pop up once you hover or click on the check mark/question mark/x

**Comment by micwoj92** [comment]
Honestly I think that it isn't really needed now that microsoft announced that you can basically install it on anything. Pretty much the only needed thing is 64bit cpu.
