### ISSUE TITLE
Indonesian Translation (New)

### ISSUE THREAD

**Issue by SamCool939** [rcmaehl/WhyNotWin11#360]
I'm gonna want to upload the translation file, but where? The translate file is just ready, but idk where I can upload that file.

**Comment by bl-ue** [comment]
Upload it here: https://github.com/rcmaehl/WhyNotWin11/blob/main/Langs/0421.lang

https://github.com/rcmaehl/WhyNotWin11/blob/main/Langs/0000-translating-guidelines.txt documents it:

>Find your language code below:
>https://www.autoitscript.com/autoit3/docs/appendix/OSLangCodes.htm
>
>Always use the latest template (0000.lang)
>**Use hex code**(number) of your language

**Comment by PriitUring** [comment]
Don't upload. It's better and easier for everyone if you edit another language file and rename the edited file before you make a pull request.

1. Verify locally how your translation looks like, by editing or adding new translation to this directory: C:\Users...\AppData\Local\WhyNotWin11\Langs
2. Read this guideline text: https://github.com/rcmaehl/WhyNotWin11/blob/main/Langs/0000-translating-guidelines.txt
3.  Open this:
https://github.com/rcmaehl/WhyNotWin11/edit/main/Langs/0000.lang
4. Right side top corner, find pencil icon (if using desktop) or three dots if using mobile to see edit option.
5. Add translation text to the right side after the "="
6. Look up, there's text (WhyNotWin11 / Langs / 0000.lang in rcmaehl:main) rename 0000.lang to 041B.lang (that's the correct Hex name for Indonesian)
7.  Underneath "Propose changes", write "Add Indonesian translation 041B.lang" instead of "Update and rename 0000.lang to ..."
8. Click Create pull request ...

If this helped then you can close this ...

**Comment by bl-ue** [comment]
>rename 0000.lang to 041B.lang (that's the correct Hex name for Indonesian)

@PriitUring per [here](https://www.autoitscript.com/autoit3/docs/appendix/OSLangCodes.htm), `041B` is for Slovak and `0421` is for Indonesian 🤔

**Comment by SamCool939** [comment]
Thanks @PriitUring for the tips and @bl-ue for the correction. #372 has been added and is ready to reviewed.

**Comment by micwoj92** [comment]
@PriitUring your instructions are wrong, if you see that new PR you can see that it shows 0000.lang as being removed because of that

**Comment by SamCool939** [comment]
I'm sorry for that, so, any fix for #372?

**Comment by bl-ue** [comment]
close (@micwoj92) :)
