### ISSUE TITLE
[Dark mode] While checking rectangle is grey with

### ISSUE THREAD

**Issue by htcfreek** [rcmaehl/WhyNotWin11#387]
**Describe the bug**
While checks are running, on dark mode the ? in the rectangle is difficult to read, because the background is to light.

**To Reproduce**
1. Start WhyNotWin11

**Expected behavior**
While checking the ? is goodto read.

**Screenshots**
![image](https://user-images.githubusercontent.com/61519853/124368326-81590c80-dc60-11eb-8ad2-1116973aea2b.png)

**Desktop (please complete the following information):**
 - OS: Win10 21H1
 - Version Dev build 

**Additional context**

**Comment by micwoj92** [comment]
I think it could be solved by making it darker gray.

**Comment by billysielu** [comment]
or maybe a spinner to indicate progress.
sometimes it takes a while and people think it's failed.

**Comment by JohnLGalt** [comment]
Anyone tried it on Win11 itself?  I could not read much in dark mode, dark bg with black text....

Yes, I know it's for running on systems prior to installing Win11 - but it also provides some really good info on currently running Win11 machines, and that's why I continue to test every build on both 10 and 11.

<img width="602" alt="15" src="https://user-images.githubusercontent.com/7432512/124385688-d9196700-dca4-11eb-9c5e-6bef39135593.png">

**Comment by micwoj92** [comment]
@JohnLGalt Please update to latest version.

**Comment by JohnLGalt** [comment]
Text is now whit e on dark bg - ty.

**Comment by JohnLGalt** [comment]
Text is now white on dark bg - ty.
