### ISSUE TITLE
Storage capacity should be handled in gigabyte, not gibibyte.

### ISSUE THREAD

**Issue by micachi** [rcmaehl/WhyNotWin11#417]
Windows treats gibibytes as gigabytes for convenience, but the Windows 11 requirement gigabytes are not. 

The required "64 GB" for Windows 11 is "59.6046 GiB". Windows then displays this as "59.6 GB".
For devices of this capacity, the official check tool displayed "64 GB", which met the requirements of Windows 11. However, in WhyNotWin11, "59.6 GB" is displayed and "NG" is displayed.

This is probably due to the difference in how GiB and GB are handled, and I think the WhyNotWin11 calculation method needs to be changed to the "correct" GB units.

**Comment by rcmaehl** [comment]
Calculation is based on Windows Explorer using GiB and I'd like to keep it that way to not cause confusion, but if we know for use that the download is 59.6 GiB, I can update the check to pass if storage is >= 59.6

![image](https://user-images.githubusercontent.com/716581/124536078-492f0680-dde5-11eb-9d2d-b6144a4392be.png)

**Comment by micachi** [comment]
As you can see in this image, the official check tool clearly calculated in gigabytes.
![image](https://user-images.githubusercontent.com/78028453/124567447-fa35af80-de7e-11eb-8eaa-9a4ff50c7e92.png)

**Comment by htcfreek** [comment]
Will be fixed soon.

Please assign me

**Comment by htcfreek** [comment]
I get the correct values in my wmi query. So I am sure we get aligned with erplorer, etc.

**Comment by htcfreek** [comment]
Work in progress.

**Comment by krystian3w** [comment]
136 gigabytes ≈ 126.65987 gibibytes

**Comment by htcfreek** [comment]
The MS "Check Health Tool" is incorrect.

**Comment by micwoj92** [comment]
@krystian3w you should do other way around and see that it is right,
because ms application rounds up to whole GBs



W dniu wtorek, 6 lipca 2021 krystian3w ***@***.***>
napisał(a):
> 136 gigabytes ≈ 126.65987 gibibytes
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/cuO5XHmmKuBKUnxH4Ho_Tj93GhNWIwHaEffyBU6Iyl8PzdWrXO7F38vFyRoAeD1rhtkki6QyV-QYVB5x2mCIKfv2qB0U9LucZVhG2sKXfu2NxB7T2zWN34AZtAjqOybtt-ZQ3yOC4WvoU64h-h4W9gg3aOHFFSYfn216snq143tgjuA4k7KYMif3uYphrq_16MlGW8JFBwL2mTPVS2EKk7CuxvaEOv-WKYDWgYKULQ=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4QI57RO3CCRR3XEJMTTWNX5RA5CNFSM473UMAY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGQUNK2Q.gif>

**Comment by krystian3w** [comment]
I can't without papper or in Calc Sheet:

https://www.wolframalpha.com/input/?i=126.65987+GiB+to+GB similar rounding in Google "box" results calculation.

**Comment by micwoj92** [comment]
I don't even know what point you are trying to make now.

**Comment by krystian3w** [comment]
I only converted values `126.98 * (2^30/10^9) ≈ 136.343737` - so MS reverted app rounded 0.34 to "0".

**Comment by htcfreek** [comment]
My plan is to get nearly the same result as in explorer (windows partition) and disk management (disk).

**Comment by micachi** [comment]
If so, why is the 64 GB model of Surface Go 2 an updatable model?

**Comment by htcfreek** [comment]
> If so, why is the 64 GB model of Surface Go 2 an updatable model?

Only Microsoft does know this.

**Comment by verdy-p** [comment]
You actually don't need 64GiB for Win11, unless you have also installed other large apps (not part of Windows itself).
A clean basic installation of Windows fits in 16GiB, the upgrade adds about 12GiB for the rollback backup, tons of logs, many temp files that are not cleaned, including 9GiB for a VSS snapshot. After each installation of Windows, I can collect these 12 GiB of dust left: "CleanMgr.exe" does not delete it, even when rtunning it in advanced mode using "cleanmgr /sageset:-1" (to set all options, not all of them being selected by the Settings Storage panel) and "cleanmgr /sagerun:-1" (to perform the actual cleaning selected). There are also many orphaned images of old versions left in WinSxS (including old drivers).
If you lack space for the upgrade, you can use a fast tool like "DISM++" to make space and remove gigabytes of dust (do that only if your system is fully updated with all security updates, and you've rebooted and your system is stable, then reboot again to assert it. Then run DISM++ cleanup. At that point you may start upgrading (if not, there are many other logs that you can find in various folders: cleanup the cache of all browsers from all users except possibly in your adminsitrator account).

For windows 11 in fact 32GB in drive C: is enough for the current clean version and installing the update, and 64Gb should not be a problem. otherwise consider moving your large files, notably collections of musics, videos or game libraries, to another drive (they don't need to be on your small SSD or internal flash storage)

One thing top consider however is to check if your disk does not have extra partitions containing different old version of Windows Recovery: you just need one partition and it should be about 550MB; as well you may easily reduve the UEFI partition to 50MB instead of 100MB or more (a tool like Partition Magic or Minitool Partition Wizard can help you check these, and can help resize the C: partition if you've added another one too large for your own files).

Why does Microsoft wants you to have 64GB free ? it assumes that you have a 128GB SSD at least. But in reality 30GB for windows and 12Gb for the space needed for the update is enough and a 64GB SSD is sufficient (especailly if you store/sync your files on the cloud and not on your PC: that's why Microsoft provided OneDrive and wants you to use it, but you can choose any other cloud provider or an external USB drive or a network volume on your LAN).

You may also want to disable temporarily the Hibernation file and reduce the size of your memory swapfile (you need to reboot for this to take an effect). to gain gigabytes. You can restore the hibernation later and static swap file later, after the upgrade if you need it on your mobile PC. I wonder why Windows does not propose it directly (windwos does not need more than 2GB of swap file for performing the upgrade, it may even not use any swapfile if you have 8GB or RAM: just close all apps, disable autostarting programs, your RAM should be enough, and anyway the second step of the upgrade in WinRE works perfectly with just 1GB of RAM and no swap file at all and it does not need any hibernation and you should not hibernate the PC during the upgrade).

Also inside a VM, Windows 11 (even Pro or Enterprise) works flawlessly with only a 30GB virtual drive and with just 2GB of virtual RAM (you can set the display resulotion to 1024x768 and a virtual GPU with just 128MB of VRAM) and two virtual CPU cores. You can use the image of your small VM to reinstall Windows on bare metal into a physical partition (a tool like CloneZilla can do that, it is even faster to perform this upgrade from a VM because your hypervisor requires much less storage space for the virtual drive, and it uses compression and may use deduplication, meaning that your virtual drive will be small and fast to reimage to your physical system partition; after the reimaging, you can remount the other partitions or extend again your system volume): a 30GB virtual drive for a VM fits inside any USB key or SD card.

**Comment by rcmaehl** [comment]
Not considering improving any further after #431. If this is reporting invalid upgrade results in any way, I'll consider reopening.

**Comment by verdy-p** [comment]
Actually you should not consider the size taken after reduction: the process of converting and installing requires additional space to extract archives, create various temporary logs to be reported (which may be compressed later), and some space for additional downloaded packages; as well the process of compiling .net packages also requires some space (this can be quitre huge when installating .net itself, or upgrading it). Finally, the existing dynamic swapfiles may be too small and will be grown during the process; upgrading some third party drivers downlaoded from windows Update may also need their own additional space (which is not always counted, however it is usually small, except for logs in complex drivers like graphics boards).
I've seen some cases where even  646GiB was not enough for the upgrade, and the upgrade failed in the middle and had to be reverted on the next reboot: we needed to perform initial cleanup of the system (for example removing old "Recovery" partitions that were no longer used, deleteing all existing logs in "\windows\logs", and "\windows\system32\LogFiles", all "*.etl" event files (including those created by third aprty apps), cleanup up web browser caches, caches of image thumbnails created by Windows Explorer: Usually on Windows, if you've never done this beore, you can easily gain at least 15GB of garbage left by Windows, application installers, independantly oif system snapshots).

If you cannot gain anything before restaring the upgrade, first create a system snapshot, delete all snapshots (this still leaves one active log), recreate a new snapshot, and cleanup snapshots once again: you'll go from a common installation of Windows taking about 55GB (or 63GB with Office apps) downto 35GB (or 51GB with Office); the milage may vary if you've installed very large apps (hint: if you used Steam, move your games library into another directory, or cleanup some games that you can resintall later if your download time is not too long; you can also backup some of your collections of videos/images/photos to an external drive to make space, even if you'll want to restore them later after the upgrade, but usually you should avoid placing them in the "C:" drive: showing/playing videos, photos and music from an HDD is not slow at all, they don't need to be on your SSD, except may be your current unfinished work files for video editing).
