### ISSUE TITLE
Wrong WDDM2 detection

### ISSUE THREAD

**Issue by totalgaara** [rcmaehl/WhyNotWin11#57]
WDDM2 is not detected on my R9 290, but DXDIAG say that i've WDDM 2.7
![wddm](https://user-images.githubusercontent.com/1378194/123536169-01471a00-d729-11eb-9d1f-930402fb63c1.png)

**Comment by famo000** [comment]
Hello, WDDM 2 is not detect correctly on my computer because there is a special char in the string after WDDM (Driver Model: WDDM 2.7). A char 160 or $A0
So i mofified the code like this : Case StringInStr($sDXFile, "DDIVersion:12") And StringInStr($sDXFile, "DriverModel:WDDM" & chr(160) & "2") .
After, the detection is OK.
I am on a french Windows.
TPM is red to, i think it's not activate in UEFI.
Thanks for the tool

**Comment by billysielu** [comment]
WDDM 3.0 fails too (not my system)
![image](https://user-images.githubusercontent.com/59173811/123540633-f0ea6b80-d737-11eb-8da9-bc964c7bd6c5.png)

**Comment by rcmaehl** [comment]
Please try the latest action build
https://github.com/rcmaehl/WhyNotWin11/suites/3096312388/artifacts/70750372

**Comment by mkody** [comment]
Had the same issue and that build works for me!

**Comment by rcmaehl** [comment]
Marking as resolved in 2.2.3
