### ISSUE TITLE
List of Threadrippers incomplete?

### ISSUE THREAD

**Issue by theonlytruth** [rcmaehl/WhyNotWin11#743]
Hey,

if I check a PC with a AMD Ryzen Threadripper 3975WX WhyNotWin11 says:

![grafik](https://github.com/rcmaehl/WhyNotWin11/assets/5502973/43cfb93e-30cc-4a5b-a1a5-73ed54e2e9bd)

But in [Microsoft's list](https://learn.microsoft.com/de-de/windows-hardware/design/minimum/supported/windows-11-supported-amd-processors) it is included. Why is it missed in your list? Maybe it's because Microsoft added them later to their list but this is some months ago.

Regards
Carsten

**Comment by theonlytruth** [comment]
Here is another example with a AMD Ryzen Threadripper 3955WX:
![3955](https://github.com/rcmaehl/WhyNotWin11/assets/5502973/c67304dd-d014-4e03-896c-201a20e04d0e)

**Comment by rcmaehl** [comment]
Can you open CPU-Z and send me a screenshot of the first page. It's probably Processor Family related.

**Comment by theonlytruth** [comment]
> Can you open CPU-Z and send me a screenshot of the first page. It's probably Processor Family related.

![grafik](https://github.com/rcmaehl/WhyNotWin11/assets/5502973/c47d0d77-da7d-41f9-abee-6461417ccee6)

![grafik](https://github.com/rcmaehl/WhyNotWin11/assets/5502973/456a05bb-ea1c-4cf9-a405-b1c5ee00ba10)

**Comment by rcmaehl** [comment]
Ah, this is because those Threadrippers are in "Family 23" (17 in hex). 

![image](https://github.com/rcmaehl/WhyNotWin11/assets/716581/ad90360a-30ce-42e0-9d7f-ef82d9469078)

As such it doesn't automatically get marked as compatible. I'll get the lists updated

![image](https://github.com/rcmaehl/WhyNotWin11/assets/716581/5736187c-6c16-40a2-be22-deafc4044fb6)

**Comment by rcmaehl** [comment]
Fixed in [65bdb38](https://github.com/rcmaehl/WhyNotWin11/commit/65bdb388aad86194126fc846adf59be44fb2a379). You can update the file manually by [downloading it here](https://raw.githubusercontent.com/rcmaehl/WhyNotWin11/2.6.1.0/includes/SupportedProcessorsAMD.txt) and putting it in `%localappdata%\WhyNotWin11`. Will work on releasing 2.6.1.0 by the end of the week
