### ISSUE TITLE
small improvement to storage check

### ISSUE THREAD

**Issue by thecatontheceiling** [rcmaehl/WhyNotWin11#751]
WhyWin11 says Windows 11 required 64 GiB storage, but in practice the Windows 11 installer only requires 52 GiB (55~ GB).

![image-75.png](https://github.com/rcmaehl/WhyNotWin11/assets/75037904/8e6c8890-9109-43f1-a181-9b87d676611d)

I suggest making a note of some kind about this or making the program not say "you're UNSUPPORTED" if you have more than 52 GiB of space.

**Comment by micwoj92** [comment]
https://support.microsoft.com/en-us/windows/windows-11-system-requirements-86c11283-ea52-4782-9efd-7674389a7ba3

**Comment by thecatontheceiling** [comment]
?
this issue explained how it's **not** 64 GB lol

**Comment by micwoj92** [comment]
I'd say keep as it is. I mean it is also possible to install windows 11 on other (unsupported) configurations and it will work fine.

What does the official tool from microsoft say?

**Comment by thecatontheceiling** [comment]
In those other cases you need to use a bypass of some kind. But in this case there was no modificatio needed for Windows 11 installer to let me install it on a 52 GB drive.

this is microsoft supported. check HwReqEval.json in sources\hwreqchk.dll:
`// Sun Valley Client requires 64 GB system drive. ~52 GB for fudge factor`

**Comment by rcmaehl** [comment]
Most commonly available storage devices are multiples of 2^X GB in size for a long time now. That 51GB disk was likely marketed as 64GB of Flash Storage. I believe WNW11 checks the size of the DISK instead of the PARTITION, but it's been a while since I even touched htcfreek's portion of code.

Maybe I'll add in some looser checks for Virtual Machines since they can have disks of any size but I don't see it being a huge deal.

**Comment by thecatontheceiling** [comment]
If I'm understanding what you said correctly, that 51 GB drive was the only disk in the laptop so it isn't a multiple-partition issue
