### ISSUE TITLE
Secure Boot is not required to be enabled

### ISSUE THREAD

**Issue by OverseerCave** [rcmaehl/WhyNotWin11#8]
This app shows a fail on Secure Boot - the [Windows 11 system requirements](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-requirements) say that the computer just has to be Secure Boot-capable (not that it has to be on, it just has to have the support for it).

Additionally, Microsoft's tool says my computer is Windows 11-compatible despite Secure Boot being disabled.

**Comment by Erisa** [comment]
Seconded, my machine also passes PC Health Check when Secure Boot is disabled. The tool mentions its secure boot-compatible so it's okay with it.

**Comment by torchgm** [comment]
Third(?)ed. It's officially documented [here](https://docs.microsoft.com/en-us/windows/compatibility/windows-11/#hardware-requirements) that the machine just needs to be Secure Boot Capable, and again mine passes the check with Secure Boot disabled.

**Comment by rcmaehl** [comment]
PC Health Check got an update, it appears to be checking Secure Boot now. I'll leave this in
![image](https://user-images.githubusercontent.com/716581/123457858-5a407200-d5b2-11eb-812b-c6d63197f236.png)

**Comment by werdnaa87** [comment]
Supporting secure boot and having it enabled are two different things though. Having it supported is all you need, that error is saying it's not supported

**Comment by Timo654** [comment]
Same here, I have Secure Boot disabled and PC Health Check says my PC meets requirements, even after the update.

**Comment by Tervel1337** [comment]
Same thing here, it says that it's fine even after the update. Yes, I have not enabled secure boot because I can't even if I wanted to due to my motherboard reenabling CSM support upon each reboot. Fingers crossed this stays this way and is not in need of being turned on but rather just being a part of your PC.
![image](https://user-images.githubusercontent.com/78919226/123466126-a4981200-d5f7-11eb-86e0-d095a3e22377.png)

**Comment by uintdev** [comment]
<img width="365" alt="P3AJWSGn4t" src="https://user-images.githubusercontent.com/6000071/123464063-3eee5a80-d5e4-11eb-8234-4c46826af34b.png">

This is what I get on the Windows Settings insider programme section. Note that it says "recommended". This implies that both soft and hard floor requirements would have to be met in order to meet the recommended hardware requirements but only hard was met in this case. Also, it leaves a word of warning as if you still have the option to proceed. This lines up with "... devices that meet the soft floor will receive a notification that upgrade is not advised" found here: https://docs.microsoft.com/en-us/windows/compatibility/windows-11/
My UEFI has secure boot support. The feature is disabled. Yet, that message is displayed. Capable is not the same as enabled. If it had to be enabled, this would've been specifically mentioned in the requirements. Custom-built PCs, for example, may not have this existing feature enabled by choice. Some pre-builts don't have it enabled by default.

The official PC Health Check app does not properly check the requirements. So in my case, it would claim that my PC cannot run Windows 11. From what was reported, this would be because it's not on the supported processor list (in my case, Intel Core 7th gen), even though it is a soft floor requirement. An update is coming soon to address issues with the check.

https://www.windowscentral.com/microsoft-working-fix-windows-11-pc-health-check-app

The check did reportedly pass on some machines with secure boot disabled. I would assume that they also have officially supported processors too.

**Comment by Theswweet** [comment]
I know I commented on LTT forums with this, but yeah - you do *not* need Secure Boot enabled on the current version of the Health Check app.
![windows11secureboot](https://user-images.githubusercontent.com/5161970/123500494-584ad300-d5f3-11eb-94c2-a0d8fc593d8d.JPG)

**Comment by rcmaehl** [comment]
Will adjust based on UEFI result in an upcoming release
